language: bash
matrix:
  include:
    - os: linux
      dist: bionic
      sudo: required
      addons:
        apt:
          packages:
            - python3
            - python3-pip
            - python3-setuptools
            - build-essential
            - fuse
            - git
      script:
        - sudo pip3 install https://codeload.github.com/zaoqi/gitfs/tar.gz/master
        - mkdir mount
        - gitfs "$HTTPS_GIT_REPO" mount
        - ls mount
